// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ExampleSensor$ReactTemplate = require("./ExampleSensor.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, ExampleSensor$ReactTemplate.make(/* array */[])), "index1");

/*  Not a pure module */
